/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AiCounselRouteImport } from './routes/ai-counsel'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CorporateFilingsRouteImport } from './routes/corporate-filings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as Form9RouteImport } from './routes/form-9'
import { Route as FormARouteImport } from './routes/form-a'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IncorporationRouteImport } from './routes/incorporation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareChangesRouteImport } from './routes/share-changes'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TaxAssistantRouteImport } from './routes/tax-assistant'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as ApproveTokenRouteImport } from './routes/approve.$token'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenChatRouteImport } from './routes/citizen.chat'
import { Route as CitizenDocumentsRouteImport } from './routes/citizen.documents'
import { Route as CitizenLawyersRouteImport } from './routes/citizen.lawyers'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as CompaniesNewRouteImport } from './routes/companies.new'
import { Route as ComplianceObligationIdRouteImport } from './routes/compliance_.$obligationId'
import { Route as ComplianceCalendarRouteImport } from './routes/compliance_.calendar'
import { Route as ComplianceRulesRouteImport } from './routes/compliance_.rules'
import { Route as ContractsTypeIdRouteImport } from './routes/contracts_.$typeId'
import { Route as HelpDeskIndexRouteImport } from './routes/help-desk.index'
import { Route as HelpDeskBouncedChequeRouteImport } from './routes/help-desk.bounced-cheque'
import { Route as HelpDeskCyberReportRouteImport } from './routes/help-desk.cyber-report'
import { Route as HelpDeskLegalNoticeRouteImport } from './routes/help-desk.legal-notice'
import { Route as HelpDeskPoliceEncounterRouteImport } from './routes/help-desk.police-encounter'
import { Route as HelpDeskRecoverMoneyRouteImport } from './routes/help-desk.recover-money'
import { Route as HelpDeskSuccessionRouteImport } from './routes/help-desk.succession'
import { Route as HelpDeskTenantProtectionRouteImport } from './routes/help-desk.tenant-protection'
import { Route as HelpDeskUtilityDisputeRouteImport } from './routes/help-desk.utility-dispute'
import { Route as MattersMatterIdRouteImport } from './routes/matters.$matterId'
import { Route as SecpIndexRouteImport } from './routes/secp.index'
import { Route as TaxIndexRouteImport } from './routes/tax.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronDeadlineRemindersRouteImport } from './routes/api/cron/deadline-reminders'
import { Route as CompaniesCompanyIdDocumentsRouteImport } from './routes/companies.$companyId_.documents'
import { Route as CompaniesCompanyIdEditRouteImport } from './routes/companies.$companyId_.edit'
import { Route as CompaniesCompanyIdEmployeesRouteImport } from './routes/companies.$companyId_.employees'
import { Route as CompaniesCompanyIdSettingsRouteImport } from './routes/companies.$companyId_.settings'
import { Route as CompaniesCompanyIdEmployeesEmployeeIdRouteImport } from './routes/companies.$companyId_.employees_.$employeeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCounselRoute = AiCounselRouteImport.update({
  id: '/ai-counsel',
  path: '/ai-counsel',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateFilingsRoute = CorporateFilingsRouteImport.update({
  id: '/corporate-filings',
  path: '/corporate-filings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const Form9Route = Form9RouteImport.update({
  id: '/form-9',
  path: '/form-9',
  getParentRoute: () => rootRouteImport,
} as any)
const FormARoute = FormARouteImport.update({
  id: '/form-a',
  path: '/form-a',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IncorporationRoute = IncorporationRouteImport.update({
  id: '/incorporation',
  path: '/incorporation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareChangesRoute = ShareChangesRouteImport.update({
  id: '/share-changes',
  path: '/share-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxAssistantRoute = TaxAssistantRouteImport.update({
  id: '/tax-assistant',
  path: '/tax-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/admin/billing',
  path: '/admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveTokenRoute = ApproveTokenRouteImport.update({
  id: '/approve/$token',
  path: '/approve/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenChatRoute = CitizenChatRouteImport.update({
  id: '/citizen/chat',
  path: '/citizen/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenDocumentsRoute = CitizenDocumentsRouteImport.update({
  id: '/citizen/documents',
  path: '/citizen/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenLawyersRoute = CitizenLawyersRouteImport.update({
  id: '/citizen/lawyers',
  path: '/citizen/lawyers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceObligationIdRoute = ComplianceObligationIdRouteImport.update({
  id: '/compliance_/$obligationId',
  path: '/compliance/$obligationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceCalendarRoute = ComplianceCalendarRouteImport.update({
  id: '/compliance_/calendar',
  path: '/compliance/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRulesRoute = ComplianceRulesRouteImport.update({
  id: '/compliance_/rules',
  path: '/compliance/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsTypeIdRoute = ContractsTypeIdRouteImport.update({
  id: '/contracts_/$typeId',
  path: '/contracts/$typeId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskIndexRoute = HelpDeskIndexRouteImport.update({
  id: '/help-desk/',
  path: '/help-desk/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskBouncedChequeRoute = HelpDeskBouncedChequeRouteImport.update({
  id: '/help-desk/bounced-cheque',
  path: '/help-desk/bounced-cheque',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskCyberReportRoute = HelpDeskCyberReportRouteImport.update({
  id: '/help-desk/cyber-report',
  path: '/help-desk/cyber-report',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskLegalNoticeRoute = HelpDeskLegalNoticeRouteImport.update({
  id: '/help-desk/legal-notice',
  path: '/help-desk/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskPoliceEncounterRoute = HelpDeskPoliceEncounterRouteImport.update({
  id: '/help-desk/police-encounter',
  path: '/help-desk/police-encounter',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskRecoverMoneyRoute = HelpDeskRecoverMoneyRouteImport.update({
  id: '/help-desk/recover-money',
  path: '/help-desk/recover-money',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskSuccessionRoute = HelpDeskSuccessionRouteImport.update({
  id: '/help-desk/succession',
  path: '/help-desk/succession',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskTenantProtectionRoute =
  HelpDeskTenantProtectionRouteImport.update({
    id: '/help-desk/tenant-protection',
    path: '/help-desk/tenant-protection',
    getParentRoute: () => rootRouteImport,
  } as any)
const HelpDeskUtilityDisputeRoute = HelpDeskUtilityDisputeRouteImport.update({
  id: '/help-desk/utility-dispute',
  path: '/help-desk/utility-dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersMatterIdRoute = MattersMatterIdRouteImport.update({
  id: '/matters/$matterId',
  path: '/matters/$matterId',
  getParentRoute: () => rootRouteImport,
} as any)
const SecpIndexRoute = SecpIndexRouteImport.update({
  id: '/secp/',
  path: '/secp/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxIndexRoute = TaxIndexRouteImport.update({
  id: '/tax/',
  path: '/tax/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDeadlineRemindersRoute =
  ApiCronDeadlineRemindersRouteImport.update({
    id: '/api/cron/deadline-reminders',
    path: '/api/cron/deadline-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanyIdDocumentsRoute =
  CompaniesCompanyIdDocumentsRouteImport.update({
    id: '/companies/$companyId_/documents',
    path: '/companies/$companyId/documents',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanyIdEditRoute = CompaniesCompanyIdEditRouteImport.update({
  id: '/companies/$companyId_/edit',
  path: '/companies/$companyId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdEmployeesRoute =
  CompaniesCompanyIdEmployeesRouteImport.update({
    id: '/companies/$companyId_/employees',
    path: '/companies/$companyId/employees',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanyIdSettingsRoute =
  CompaniesCompanyIdSettingsRouteImport.update({
    id: '/companies/$companyId_/settings',
    path: '/companies/$companyId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanyIdEmployeesEmployeeIdRoute =
  CompaniesCompanyIdEmployeesEmployeeIdRouteImport.update({
    id: '/companies/$companyId_/employees_/$employeeId',
    path: '/companies/$companyId/employees/$employeeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ai-counsel': typeof AiCounselRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/compliance': typeof ComplianceRoute
  '/consult': typeof ConsultRoute
  '/consultations': typeof ConsultationsRoute
  '/contracts': typeof ContractsRoute
  '/corporate-filings': typeof CorporateFilingsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
  '/incorporation': typeof IncorporationRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/personal': typeof PersonalRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/share-changes': typeof ShareChangesRoute
  '/signup': typeof SignupRoute
  '/tax-assistant': typeof TaxAssistantRoute
  '/terms': typeof TermsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/citizen/chat': typeof CitizenChatRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/lawyers': typeof CitizenLawyersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/compliance/$obligationId': typeof ComplianceObligationIdRoute
  '/compliance/calendar': typeof ComplianceCalendarRoute
  '/compliance/rules': typeof ComplianceRulesRoute
  '/contracts/$typeId': typeof ContractsTypeIdRoute
  '/help-desk/bounced-cheque': typeof HelpDeskBouncedChequeRoute
  '/help-desk/cyber-report': typeof HelpDeskCyberReportRoute
  '/help-desk/legal-notice': typeof HelpDeskLegalNoticeRoute
  '/help-desk/police-encounter': typeof HelpDeskPoliceEncounterRoute
  '/help-desk/recover-money': typeof HelpDeskRecoverMoneyRoute
  '/help-desk/succession': typeof HelpDeskSuccessionRoute
  '/help-desk/tenant-protection': typeof HelpDeskTenantProtectionRoute
  '/help-desk/utility-dispute': typeof HelpDeskUtilityDisputeRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/citizen/': typeof CitizenIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/help-desk/': typeof HelpDeskIndexRoute
  '/secp/': typeof SecpIndexRoute
  '/tax/': typeof TaxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/deadline-reminders': typeof ApiCronDeadlineRemindersRoute
  '/companies/$companyId/documents': typeof CompaniesCompanyIdDocumentsRoute
  '/companies/$companyId/edit': typeof CompaniesCompanyIdEditRoute
  '/companies/$companyId/employees': typeof CompaniesCompanyIdEmployeesRoute
  '/companies/$companyId/settings': typeof CompaniesCompanyIdSettingsRoute
  '/companies/$companyId/employees/$employeeId': typeof CompaniesCompanyIdEmployeesEmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ai-counsel': typeof AiCounselRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/compliance': typeof ComplianceRoute
  '/consult': typeof ConsultRoute
  '/consultations': typeof ConsultationsRoute
  '/contracts': typeof ContractsRoute
  '/corporate-filings': typeof CorporateFilingsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
  '/incorporation': typeof IncorporationRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/personal': typeof PersonalRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/share-changes': typeof ShareChangesRoute
  '/signup': typeof SignupRoute
  '/tax-assistant': typeof TaxAssistantRoute
  '/terms': typeof TermsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/citizen/chat': typeof CitizenChatRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/lawyers': typeof CitizenLawyersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/compliance/$obligationId': typeof ComplianceObligationIdRoute
  '/compliance/calendar': typeof ComplianceCalendarRoute
  '/compliance/rules': typeof ComplianceRulesRoute
  '/contracts/$typeId': typeof ContractsTypeIdRoute
  '/help-desk/bounced-cheque': typeof HelpDeskBouncedChequeRoute
  '/help-desk/cyber-report': typeof HelpDeskCyberReportRoute
  '/help-desk/legal-notice': typeof HelpDeskLegalNoticeRoute
  '/help-desk/police-encounter': typeof HelpDeskPoliceEncounterRoute
  '/help-desk/recover-money': typeof HelpDeskRecoverMoneyRoute
  '/help-desk/succession': typeof HelpDeskSuccessionRoute
  '/help-desk/tenant-protection': typeof HelpDeskTenantProtectionRoute
  '/help-desk/utility-dispute': typeof HelpDeskUtilityDisputeRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/citizen': typeof CitizenIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/help-desk': typeof HelpDeskIndexRoute
  '/secp': typeof SecpIndexRoute
  '/tax': typeof TaxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/deadline-reminders': typeof ApiCronDeadlineRemindersRoute
  '/companies/$companyId/documents': typeof CompaniesCompanyIdDocumentsRoute
  '/companies/$companyId/edit': typeof CompaniesCompanyIdEditRoute
  '/companies/$companyId/employees': typeof CompaniesCompanyIdEmployeesRoute
  '/companies/$companyId/settings': typeof CompaniesCompanyIdSettingsRoute
  '/companies/$companyId/employees/$employeeId': typeof CompaniesCompanyIdEmployeesEmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/ai-counsel': typeof AiCounselRoute
  '/billing': typeof BillingRoute
  '/business': typeof BusinessRoute
  '/compliance': typeof ComplianceRoute
  '/consult': typeof ConsultRoute
  '/consultations': typeof ConsultationsRoute
  '/contracts': typeof ContractsRoute
  '/corporate-filings': typeof CorporateFilingsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
  '/incorporation': typeof IncorporationRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/personal': typeof PersonalRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/share-changes': typeof ShareChangesRoute
  '/signup': typeof SignupRoute
  '/tax-assistant': typeof TaxAssistantRoute
  '/terms': typeof TermsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/citizen/chat': typeof CitizenChatRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/lawyers': typeof CitizenLawyersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/compliance_/$obligationId': typeof ComplianceObligationIdRoute
  '/compliance_/calendar': typeof ComplianceCalendarRoute
  '/compliance_/rules': typeof ComplianceRulesRoute
  '/contracts_/$typeId': typeof ContractsTypeIdRoute
  '/help-desk/bounced-cheque': typeof HelpDeskBouncedChequeRoute
  '/help-desk/cyber-report': typeof HelpDeskCyberReportRoute
  '/help-desk/legal-notice': typeof HelpDeskLegalNoticeRoute
  '/help-desk/police-encounter': typeof HelpDeskPoliceEncounterRoute
  '/help-desk/recover-money': typeof HelpDeskRecoverMoneyRoute
  '/help-desk/succession': typeof HelpDeskSuccessionRoute
  '/help-desk/tenant-protection': typeof HelpDeskTenantProtectionRoute
  '/help-desk/utility-dispute': typeof HelpDeskUtilityDisputeRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/citizen/': typeof CitizenIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/help-desk/': typeof HelpDeskIndexRoute
  '/secp/': typeof SecpIndexRoute
  '/tax/': typeof TaxIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/deadline-reminders': typeof ApiCronDeadlineRemindersRoute
  '/companies/$companyId_/documents': typeof CompaniesCompanyIdDocumentsRoute
  '/companies/$companyId_/edit': typeof CompaniesCompanyIdEditRoute
  '/companies/$companyId_/employees': typeof CompaniesCompanyIdEmployeesRoute
  '/companies/$companyId_/settings': typeof CompaniesCompanyIdSettingsRoute
  '/companies/$companyId_/employees_/$employeeId': typeof CompaniesCompanyIdEmployeesEmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/ai-counsel'
    | '/billing'
    | '/business'
    | '/compliance'
    | '/consult'
    | '/consultations'
    | '/contracts'
    | '/corporate-filings'
    | '/dashboard'
    | '/documents'
    | '/form-9'
    | '/form-a'
    | '/guide'
    | '/incorporation'
    | '/login'
    | '/notices'
    | '/personal'
    | '/privacy'
    | '/settings'
    | '/share-changes'
    | '/signup'
    | '/tax-assistant'
    | '/terms'
    | '/admin/billing'
    | '/approve/$token'
    | '/citizen/chat'
    | '/citizen/documents'
    | '/citizen/lawyers'
    | '/companies/$companyId'
    | '/companies/new'
    | '/compliance/$obligationId'
    | '/compliance/calendar'
    | '/compliance/rules'
    | '/contracts/$typeId'
    | '/help-desk/bounced-cheque'
    | '/help-desk/cyber-report'
    | '/help-desk/legal-notice'
    | '/help-desk/police-encounter'
    | '/help-desk/recover-money'
    | '/help-desk/succession'
    | '/help-desk/tenant-protection'
    | '/help-desk/utility-dispute'
    | '/matters/$matterId'
    | '/citizen/'
    | '/companies/'
    | '/help-desk/'
    | '/secp/'
    | '/tax/'
    | '/api/auth/$'
    | '/api/cron/deadline-reminders'
    | '/companies/$companyId/documents'
    | '/companies/$companyId/edit'
    | '/companies/$companyId/employees'
    | '/companies/$companyId/settings'
    | '/companies/$companyId/employees/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/ai-counsel'
    | '/billing'
    | '/business'
    | '/compliance'
    | '/consult'
    | '/consultations'
    | '/contracts'
    | '/corporate-filings'
    | '/dashboard'
    | '/documents'
    | '/form-9'
    | '/form-a'
    | '/guide'
    | '/incorporation'
    | '/login'
    | '/notices'
    | '/personal'
    | '/privacy'
    | '/settings'
    | '/share-changes'
    | '/signup'
    | '/tax-assistant'
    | '/terms'
    | '/admin/billing'
    | '/approve/$token'
    | '/citizen/chat'
    | '/citizen/documents'
    | '/citizen/lawyers'
    | '/companies/$companyId'
    | '/companies/new'
    | '/compliance/$obligationId'
    | '/compliance/calendar'
    | '/compliance/rules'
    | '/contracts/$typeId'
    | '/help-desk/bounced-cheque'
    | '/help-desk/cyber-report'
    | '/help-desk/legal-notice'
    | '/help-desk/police-encounter'
    | '/help-desk/recover-money'
    | '/help-desk/succession'
    | '/help-desk/tenant-protection'
    | '/help-desk/utility-dispute'
    | '/matters/$matterId'
    | '/citizen'
    | '/companies'
    | '/help-desk'
    | '/secp'
    | '/tax'
    | '/api/auth/$'
    | '/api/cron/deadline-reminders'
    | '/companies/$companyId/documents'
    | '/companies/$companyId/edit'
    | '/companies/$companyId/employees'
    | '/companies/$companyId/settings'
    | '/companies/$companyId/employees/$employeeId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/ai-counsel'
    | '/billing'
    | '/business'
    | '/compliance'
    | '/consult'
    | '/consultations'
    | '/contracts'
    | '/corporate-filings'
    | '/dashboard'
    | '/documents'
    | '/form-9'
    | '/form-a'
    | '/guide'
    | '/incorporation'
    | '/login'
    | '/notices'
    | '/personal'
    | '/privacy'
    | '/settings'
    | '/share-changes'
    | '/signup'
    | '/tax-assistant'
    | '/terms'
    | '/admin/billing'
    | '/approve/$token'
    | '/citizen/chat'
    | '/citizen/documents'
    | '/citizen/lawyers'
    | '/companies/$companyId'
    | '/companies/new'
    | '/compliance_/$obligationId'
    | '/compliance_/calendar'
    | '/compliance_/rules'
    | '/contracts_/$typeId'
    | '/help-desk/bounced-cheque'
    | '/help-desk/cyber-report'
    | '/help-desk/legal-notice'
    | '/help-desk/police-encounter'
    | '/help-desk/recover-money'
    | '/help-desk/succession'
    | '/help-desk/tenant-protection'
    | '/help-desk/utility-dispute'
    | '/matters/$matterId'
    | '/citizen/'
    | '/companies/'
    | '/help-desk/'
    | '/secp/'
    | '/tax/'
    | '/api/auth/$'
    | '/api/cron/deadline-reminders'
    | '/companies/$companyId_/documents'
    | '/companies/$companyId_/edit'
    | '/companies/$companyId_/employees'
    | '/companies/$companyId_/settings'
    | '/companies/$companyId_/employees_/$employeeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AiCounselRoute: typeof AiCounselRoute
  BillingRoute: typeof BillingRoute
  BusinessRoute: typeof BusinessRoute
  ComplianceRoute: typeof ComplianceRoute
  ConsultRoute: typeof ConsultRoute
  ConsultationsRoute: typeof ConsultationsRoute
  ContractsRoute: typeof ContractsRoute
  CorporateFilingsRoute: typeof CorporateFilingsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  Form9Route: typeof Form9Route
  FormARoute: typeof FormARoute
  GuideRoute: typeof GuideRoute
  IncorporationRoute: typeof IncorporationRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  PersonalRoute: typeof PersonalRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  ShareChangesRoute: typeof ShareChangesRoute
  SignupRoute: typeof SignupRoute
  TaxAssistantRoute: typeof TaxAssistantRoute
  TermsRoute: typeof TermsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  ApproveTokenRoute: typeof ApproveTokenRoute
  CitizenChatRoute: typeof CitizenChatRoute
  CitizenDocumentsRoute: typeof CitizenDocumentsRoute
  CitizenLawyersRoute: typeof CitizenLawyersRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesNewRoute: typeof CompaniesNewRoute
  ComplianceObligationIdRoute: typeof ComplianceObligationIdRoute
  ComplianceCalendarRoute: typeof ComplianceCalendarRoute
  ComplianceRulesRoute: typeof ComplianceRulesRoute
  ContractsTypeIdRoute: typeof ContractsTypeIdRoute
  HelpDeskBouncedChequeRoute: typeof HelpDeskBouncedChequeRoute
  HelpDeskCyberReportRoute: typeof HelpDeskCyberReportRoute
  HelpDeskLegalNoticeRoute: typeof HelpDeskLegalNoticeRoute
  HelpDeskPoliceEncounterRoute: typeof HelpDeskPoliceEncounterRoute
  HelpDeskRecoverMoneyRoute: typeof HelpDeskRecoverMoneyRoute
  HelpDeskSuccessionRoute: typeof HelpDeskSuccessionRoute
  HelpDeskTenantProtectionRoute: typeof HelpDeskTenantProtectionRoute
  HelpDeskUtilityDisputeRoute: typeof HelpDeskUtilityDisputeRoute
  MattersMatterIdRoute: typeof MattersMatterIdRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  HelpDeskIndexRoute: typeof HelpDeskIndexRoute
  SecpIndexRoute: typeof SecpIndexRoute
  TaxIndexRoute: typeof TaxIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDeadlineRemindersRoute: typeof ApiCronDeadlineRemindersRoute
  CompaniesCompanyIdDocumentsRoute: typeof CompaniesCompanyIdDocumentsRoute
  CompaniesCompanyIdEditRoute: typeof CompaniesCompanyIdEditRoute
  CompaniesCompanyIdEmployeesRoute: typeof CompaniesCompanyIdEmployeesRoute
  CompaniesCompanyIdSettingsRoute: typeof CompaniesCompanyIdSettingsRoute
  CompaniesCompanyIdEmployeesEmployeeIdRoute: typeof CompaniesCompanyIdEmployeesEmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-counsel': {
      id: '/ai-counsel'
      path: '/ai-counsel'
      fullPath: '/ai-counsel'
      preLoaderRoute: typeof AiCounselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-filings': {
      id: '/corporate-filings'
      path: '/corporate-filings'
      fullPath: '/corporate-filings'
      preLoaderRoute: typeof CorporateFilingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-9': {
      id: '/form-9'
      path: '/form-9'
      fullPath: '/form-9'
      preLoaderRoute: typeof Form9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-a': {
      id: '/form-a'
      path: '/form-a'
      fullPath: '/form-a'
      preLoaderRoute: typeof FormARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incorporation': {
      id: '/incorporation'
      path: '/incorporation'
      fullPath: '/incorporation'
      preLoaderRoute: typeof IncorporationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-changes': {
      id: '/share-changes'
      path: '/share-changes'
      fullPath: '/share-changes'
      preLoaderRoute: typeof ShareChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-assistant': {
      id: '/tax-assistant'
      path: '/tax-assistant'
      fullPath: '/tax-assistant'
      preLoaderRoute: typeof TaxAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve/$token': {
      id: '/approve/$token'
      path: '/approve/$token'
      fullPath: '/approve/$token'
      preLoaderRoute: typeof ApproveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/chat': {
      id: '/citizen/chat'
      path: '/citizen/chat'
      fullPath: '/citizen/chat'
      preLoaderRoute: typeof CitizenChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/documents': {
      id: '/citizen/documents'
      path: '/citizen/documents'
      fullPath: '/citizen/documents'
      preLoaderRoute: typeof CitizenDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/lawyers': {
      id: '/citizen/lawyers'
      path: '/citizen/lawyers'
      fullPath: '/citizen/lawyers'
      preLoaderRoute: typeof CitizenLawyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/companies/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/$obligationId': {
      id: '/compliance_/$obligationId'
      path: '/compliance/$obligationId'
      fullPath: '/compliance/$obligationId'
      preLoaderRoute: typeof ComplianceObligationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/calendar': {
      id: '/compliance_/calendar'
      path: '/compliance/calendar'
      fullPath: '/compliance/calendar'
      preLoaderRoute: typeof ComplianceCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance_/rules': {
      id: '/compliance_/rules'
      path: '/compliance/rules'
      fullPath: '/compliance/rules'
      preLoaderRoute: typeof ComplianceRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts_/$typeId': {
      id: '/contracts_/$typeId'
      path: '/contracts/$typeId'
      fullPath: '/contracts/$typeId'
      preLoaderRoute: typeof ContractsTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/': {
      id: '/help-desk/'
      path: '/help-desk'
      fullPath: '/help-desk/'
      preLoaderRoute: typeof HelpDeskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/bounced-cheque': {
      id: '/help-desk/bounced-cheque'
      path: '/help-desk/bounced-cheque'
      fullPath: '/help-desk/bounced-cheque'
      preLoaderRoute: typeof HelpDeskBouncedChequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/cyber-report': {
      id: '/help-desk/cyber-report'
      path: '/help-desk/cyber-report'
      fullPath: '/help-desk/cyber-report'
      preLoaderRoute: typeof HelpDeskCyberReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/legal-notice': {
      id: '/help-desk/legal-notice'
      path: '/help-desk/legal-notice'
      fullPath: '/help-desk/legal-notice'
      preLoaderRoute: typeof HelpDeskLegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/police-encounter': {
      id: '/help-desk/police-encounter'
      path: '/help-desk/police-encounter'
      fullPath: '/help-desk/police-encounter'
      preLoaderRoute: typeof HelpDeskPoliceEncounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/recover-money': {
      id: '/help-desk/recover-money'
      path: '/help-desk/recover-money'
      fullPath: '/help-desk/recover-money'
      preLoaderRoute: typeof HelpDeskRecoverMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/succession': {
      id: '/help-desk/succession'
      path: '/help-desk/succession'
      fullPath: '/help-desk/succession'
      preLoaderRoute: typeof HelpDeskSuccessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/tenant-protection': {
      id: '/help-desk/tenant-protection'
      path: '/help-desk/tenant-protection'
      fullPath: '/help-desk/tenant-protection'
      preLoaderRoute: typeof HelpDeskTenantProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/utility-dispute': {
      id: '/help-desk/utility-dispute'
      path: '/help-desk/utility-dispute'
      fullPath: '/help-desk/utility-dispute'
      preLoaderRoute: typeof HelpDeskUtilityDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$matterId': {
      id: '/matters/$matterId'
      path: '/matters/$matterId'
      fullPath: '/matters/$matterId'
      preLoaderRoute: typeof MattersMatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secp/': {
      id: '/secp/'
      path: '/secp'
      fullPath: '/secp/'
      preLoaderRoute: typeof SecpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/': {
      id: '/tax/'
      path: '/tax'
      fullPath: '/tax/'
      preLoaderRoute: typeof TaxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/deadline-reminders': {
      id: '/api/cron/deadline-reminders'
      path: '/api/cron/deadline-reminders'
      fullPath: '/api/cron/deadline-reminders'
      preLoaderRoute: typeof ApiCronDeadlineRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId_/documents': {
      id: '/companies/$companyId_/documents'
      path: '/companies/$companyId/documents'
      fullPath: '/companies/$companyId/documents'
      preLoaderRoute: typeof CompaniesCompanyIdDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId_/edit': {
      id: '/companies/$companyId_/edit'
      path: '/companies/$companyId/edit'
      fullPath: '/companies/$companyId/edit'
      preLoaderRoute: typeof CompaniesCompanyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId_/employees': {
      id: '/companies/$companyId_/employees'
      path: '/companies/$companyId/employees'
      fullPath: '/companies/$companyId/employees'
      preLoaderRoute: typeof CompaniesCompanyIdEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId_/settings': {
      id: '/companies/$companyId_/settings'
      path: '/companies/$companyId/settings'
      fullPath: '/companies/$companyId/settings'
      preLoaderRoute: typeof CompaniesCompanyIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId_/employees_/$employeeId': {
      id: '/companies/$companyId_/employees_/$employeeId'
      path: '/companies/$companyId/employees/$employeeId'
      fullPath: '/companies/$companyId/employees/$employeeId'
      preLoaderRoute: typeof CompaniesCompanyIdEmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AiCounselRoute: AiCounselRoute,
  BillingRoute: BillingRoute,
  BusinessRoute: BusinessRoute,
  ComplianceRoute: ComplianceRoute,
  ConsultRoute: ConsultRoute,
  ConsultationsRoute: ConsultationsRoute,
  ContractsRoute: ContractsRoute,
  CorporateFilingsRoute: CorporateFilingsRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  Form9Route: Form9Route,
  FormARoute: FormARoute,
  GuideRoute: GuideRoute,
  IncorporationRoute: IncorporationRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  PersonalRoute: PersonalRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  ShareChangesRoute: ShareChangesRoute,
  SignupRoute: SignupRoute,
  TaxAssistantRoute: TaxAssistantRoute,
  TermsRoute: TermsRoute,
  AdminBillingRoute: AdminBillingRoute,
  ApproveTokenRoute: ApproveTokenRoute,
  CitizenChatRoute: CitizenChatRoute,
  CitizenDocumentsRoute: CitizenDocumentsRoute,
  CitizenLawyersRoute: CitizenLawyersRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesNewRoute: CompaniesNewRoute,
  ComplianceObligationIdRoute: ComplianceObligationIdRoute,
  ComplianceCalendarRoute: ComplianceCalendarRoute,
  ComplianceRulesRoute: ComplianceRulesRoute,
  ContractsTypeIdRoute: ContractsTypeIdRoute,
  HelpDeskBouncedChequeRoute: HelpDeskBouncedChequeRoute,
  HelpDeskCyberReportRoute: HelpDeskCyberReportRoute,
  HelpDeskLegalNoticeRoute: HelpDeskLegalNoticeRoute,
  HelpDeskPoliceEncounterRoute: HelpDeskPoliceEncounterRoute,
  HelpDeskRecoverMoneyRoute: HelpDeskRecoverMoneyRoute,
  HelpDeskSuccessionRoute: HelpDeskSuccessionRoute,
  HelpDeskTenantProtectionRoute: HelpDeskTenantProtectionRoute,
  HelpDeskUtilityDisputeRoute: HelpDeskUtilityDisputeRoute,
  MattersMatterIdRoute: MattersMatterIdRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  HelpDeskIndexRoute: HelpDeskIndexRoute,
  SecpIndexRoute: SecpIndexRoute,
  TaxIndexRoute: TaxIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDeadlineRemindersRoute: ApiCronDeadlineRemindersRoute,
  CompaniesCompanyIdDocumentsRoute: CompaniesCompanyIdDocumentsRoute,
  CompaniesCompanyIdEditRoute: CompaniesCompanyIdEditRoute,
  CompaniesCompanyIdEmployeesRoute: CompaniesCompanyIdEmployeesRoute,
  CompaniesCompanyIdSettingsRoute: CompaniesCompanyIdSettingsRoute,
  CompaniesCompanyIdEmployeesEmployeeIdRoute:
    CompaniesCompanyIdEmployeesEmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
