/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CorporateFilingsRouteImport } from './routes/corporate-filings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Form9RouteImport } from './routes/form-9'
import { Route as FormARouteImport } from './routes/form-a'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IncorporationRouteImport } from './routes/incorporation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TaxAssistantRouteImport } from './routes/tax-assistant'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApproveTokenRouteImport } from './routes/approve.$token'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenChatRouteImport } from './routes/citizen.chat'
import { Route as CitizenDocumentsRouteImport } from './routes/citizen.documents'
import { Route as CitizenLawyersRouteImport } from './routes/citizen.lawyers'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'
import { Route as CompaniesNewRouteImport } from './routes/companies.new'
import { Route as HelpDeskIndexRouteImport } from './routes/help-desk.index'
import { Route as HelpDeskCyberReportRouteImport } from './routes/help-desk.cyber-report'
import { Route as HelpDeskPoliceEncounterRouteImport } from './routes/help-desk.police-encounter'
import { Route as HelpDeskSuccessionRouteImport } from './routes/help-desk.succession'
import { Route as HelpDeskTenantProtectionRouteImport } from './routes/help-desk.tenant-protection'
import { Route as HelpDeskUtilityDisputeRouteImport } from './routes/help-desk.utility-dispute'
import { Route as MattersMatterIdRouteImport } from './routes/matters.$matterId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronDeadlineRemindersRouteImport } from './routes/api/cron/deadline-reminders'
import { Route as CompaniesCompanyIdEditRouteImport } from './routes/companies.$companyId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateFilingsRoute = CorporateFilingsRouteImport.update({
  id: '/corporate-filings',
  path: '/corporate-filings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Form9Route = Form9RouteImport.update({
  id: '/form-9',
  path: '/form-9',
  getParentRoute: () => rootRouteImport,
} as any)
const FormARoute = FormARouteImport.update({
  id: '/form-a',
  path: '/form-a',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IncorporationRoute = IncorporationRouteImport.update({
  id: '/incorporation',
  path: '/incorporation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxAssistantRoute = TaxAssistantRouteImport.update({
  id: '/tax-assistant',
  path: '/tax-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveTokenRoute = ApproveTokenRouteImport.update({
  id: '/approve/$token',
  path: '/approve/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenChatRoute = CitizenChatRouteImport.update({
  id: '/citizen/chat',
  path: '/citizen/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenDocumentsRoute = CitizenDocumentsRouteImport.update({
  id: '/citizen/documents',
  path: '/citizen/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenLawyersRoute = CitizenLawyersRouteImport.update({
  id: '/citizen/lawyers',
  path: '/citizen/lawyers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskIndexRoute = HelpDeskIndexRouteImport.update({
  id: '/help-desk/',
  path: '/help-desk/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskCyberReportRoute = HelpDeskCyberReportRouteImport.update({
  id: '/help-desk/cyber-report',
  path: '/help-desk/cyber-report',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskPoliceEncounterRoute = HelpDeskPoliceEncounterRouteImport.update({
  id: '/help-desk/police-encounter',
  path: '/help-desk/police-encounter',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskSuccessionRoute = HelpDeskSuccessionRouteImport.update({
  id: '/help-desk/succession',
  path: '/help-desk/succession',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskTenantProtectionRoute =
  HelpDeskTenantProtectionRouteImport.update({
    id: '/help-desk/tenant-protection',
    path: '/help-desk/tenant-protection',
    getParentRoute: () => rootRouteImport,
  } as any)
const HelpDeskUtilityDisputeRoute = HelpDeskUtilityDisputeRouteImport.update({
  id: '/help-desk/utility-dispute',
  path: '/help-desk/utility-dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersMatterIdRoute = MattersMatterIdRouteImport.update({
  id: '/matters/$matterId',
  path: '/matters/$matterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDeadlineRemindersRoute =
  ApiCronDeadlineRemindersRouteImport.update({
    id: '/api/cron/deadline-reminders',
    path: '/api/cron/deadline-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanyIdEditRoute = CompaniesCompanyIdEditRouteImport.update({
  id: '/companies/$companyId_/edit',
  path: '/companies/$companyId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/compliance': typeof ComplianceRoute
  '/consult': typeof ConsultRoute
  '/consultations': typeof ConsultationsRoute
  '/contracts': typeof ContractsRoute
  '/corporate-filings': typeof CorporateFilingsRoute
  '/dashboard': typeof DashboardRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
  '/incorporation': typeof IncorporationRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/tax-assistant': typeof TaxAssistantRoute
  '/terms': typeof TermsRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/citizen/chat': typeof CitizenChatRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/lawyers': typeof CitizenLawyersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/help-desk/cyber-report': typeof HelpDeskCyberReportRoute
  '/help-desk/police-encounter': typeof HelpDeskPoliceEncounterRoute
  '/help-desk/succession': typeof HelpDeskSuccessionRoute
  '/help-desk/tenant-protection': typeof HelpDeskTenantProtectionRoute
  '/help-desk/utility-dispute': typeof HelpDeskUtilityDisputeRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/citizen/': typeof CitizenIndexRoute
  '/help-desk/': typeof HelpDeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/deadline-reminders': typeof ApiCronDeadlineRemindersRoute
  '/companies/$companyId/edit': typeof CompaniesCompanyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/compliance': typeof ComplianceRoute
  '/consult': typeof ConsultRoute
  '/consultations': typeof ConsultationsRoute
  '/contracts': typeof ContractsRoute
  '/corporate-filings': typeof CorporateFilingsRoute
  '/dashboard': typeof DashboardRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
  '/incorporation': typeof IncorporationRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/tax-assistant': typeof TaxAssistantRoute
  '/terms': typeof TermsRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/citizen/chat': typeof CitizenChatRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/lawyers': typeof CitizenLawyersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/help-desk/cyber-report': typeof HelpDeskCyberReportRoute
  '/help-desk/police-encounter': typeof HelpDeskPoliceEncounterRoute
  '/help-desk/succession': typeof HelpDeskSuccessionRoute
  '/help-desk/tenant-protection': typeof HelpDeskTenantProtectionRoute
  '/help-desk/utility-dispute': typeof HelpDeskUtilityDisputeRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/citizen': typeof CitizenIndexRoute
  '/help-desk': typeof HelpDeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/deadline-reminders': typeof ApiCronDeadlineRemindersRoute
  '/companies/$companyId/edit': typeof CompaniesCompanyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/compliance': typeof ComplianceRoute
  '/consult': typeof ConsultRoute
  '/consultations': typeof ConsultationsRoute
  '/contracts': typeof ContractsRoute
  '/corporate-filings': typeof CorporateFilingsRoute
  '/dashboard': typeof DashboardRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
  '/incorporation': typeof IncorporationRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/tax-assistant': typeof TaxAssistantRoute
  '/terms': typeof TermsRoute
  '/approve/$token': typeof ApproveTokenRoute
  '/citizen/chat': typeof CitizenChatRoute
  '/citizen/documents': typeof CitizenDocumentsRoute
  '/citizen/lawyers': typeof CitizenLawyersRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/new': typeof CompaniesNewRoute
  '/help-desk/cyber-report': typeof HelpDeskCyberReportRoute
  '/help-desk/police-encounter': typeof HelpDeskPoliceEncounterRoute
  '/help-desk/succession': typeof HelpDeskSuccessionRoute
  '/help-desk/tenant-protection': typeof HelpDeskTenantProtectionRoute
  '/help-desk/utility-dispute': typeof HelpDeskUtilityDisputeRoute
  '/matters/$matterId': typeof MattersMatterIdRoute
  '/citizen/': typeof CitizenIndexRoute
  '/help-desk/': typeof HelpDeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/deadline-reminders': typeof ApiCronDeadlineRemindersRoute
  '/companies/$companyId_/edit': typeof CompaniesCompanyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/compliance'
    | '/consult'
    | '/consultations'
    | '/contracts'
    | '/corporate-filings'
    | '/dashboard'
    | '/form-9'
    | '/form-a'
    | '/guide'
    | '/incorporation'
    | '/login'
    | '/notices'
    | '/privacy'
    | '/signup'
    | '/tax-assistant'
    | '/terms'
    | '/approve/$token'
    | '/citizen/chat'
    | '/citizen/documents'
    | '/citizen/lawyers'
    | '/companies/$companyId'
    | '/companies/new'
    | '/help-desk/cyber-report'
    | '/help-desk/police-encounter'
    | '/help-desk/succession'
    | '/help-desk/tenant-protection'
    | '/help-desk/utility-dispute'
    | '/matters/$matterId'
    | '/citizen/'
    | '/help-desk/'
    | '/api/auth/$'
    | '/api/cron/deadline-reminders'
    | '/companies/$companyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/compliance'
    | '/consult'
    | '/consultations'
    | '/contracts'
    | '/corporate-filings'
    | '/dashboard'
    | '/form-9'
    | '/form-a'
    | '/guide'
    | '/incorporation'
    | '/login'
    | '/notices'
    | '/privacy'
    | '/signup'
    | '/tax-assistant'
    | '/terms'
    | '/approve/$token'
    | '/citizen/chat'
    | '/citizen/documents'
    | '/citizen/lawyers'
    | '/companies/$companyId'
    | '/companies/new'
    | '/help-desk/cyber-report'
    | '/help-desk/police-encounter'
    | '/help-desk/succession'
    | '/help-desk/tenant-protection'
    | '/help-desk/utility-dispute'
    | '/matters/$matterId'
    | '/citizen'
    | '/help-desk'
    | '/api/auth/$'
    | '/api/cron/deadline-reminders'
    | '/companies/$companyId/edit'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/compliance'
    | '/consult'
    | '/consultations'
    | '/contracts'
    | '/corporate-filings'
    | '/dashboard'
    | '/form-9'
    | '/form-a'
    | '/guide'
    | '/incorporation'
    | '/login'
    | '/notices'
    | '/privacy'
    | '/signup'
    | '/tax-assistant'
    | '/terms'
    | '/approve/$token'
    | '/citizen/chat'
    | '/citizen/documents'
    | '/citizen/lawyers'
    | '/companies/$companyId'
    | '/companies/new'
    | '/help-desk/cyber-report'
    | '/help-desk/police-encounter'
    | '/help-desk/succession'
    | '/help-desk/tenant-protection'
    | '/help-desk/utility-dispute'
    | '/matters/$matterId'
    | '/citizen/'
    | '/help-desk/'
    | '/api/auth/$'
    | '/api/cron/deadline-reminders'
    | '/companies/$companyId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ComplianceRoute: typeof ComplianceRoute
  ConsultRoute: typeof ConsultRoute
  ConsultationsRoute: typeof ConsultationsRoute
  ContractsRoute: typeof ContractsRoute
  CorporateFilingsRoute: typeof CorporateFilingsRoute
  DashboardRoute: typeof DashboardRoute
  Form9Route: typeof Form9Route
  FormARoute: typeof FormARoute
  GuideRoute: typeof GuideRoute
  IncorporationRoute: typeof IncorporationRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TaxAssistantRoute: typeof TaxAssistantRoute
  TermsRoute: typeof TermsRoute
  ApproveTokenRoute: typeof ApproveTokenRoute
  CitizenChatRoute: typeof CitizenChatRoute
  CitizenDocumentsRoute: typeof CitizenDocumentsRoute
  CitizenLawyersRoute: typeof CitizenLawyersRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesNewRoute: typeof CompaniesNewRoute
  HelpDeskCyberReportRoute: typeof HelpDeskCyberReportRoute
  HelpDeskPoliceEncounterRoute: typeof HelpDeskPoliceEncounterRoute
  HelpDeskSuccessionRoute: typeof HelpDeskSuccessionRoute
  HelpDeskTenantProtectionRoute: typeof HelpDeskTenantProtectionRoute
  HelpDeskUtilityDisputeRoute: typeof HelpDeskUtilityDisputeRoute
  MattersMatterIdRoute: typeof MattersMatterIdRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  HelpDeskIndexRoute: typeof HelpDeskIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDeadlineRemindersRoute: typeof ApiCronDeadlineRemindersRoute
  CompaniesCompanyIdEditRoute: typeof CompaniesCompanyIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-filings': {
      id: '/corporate-filings'
      path: '/corporate-filings'
      fullPath: '/corporate-filings'
      preLoaderRoute: typeof CorporateFilingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-9': {
      id: '/form-9'
      path: '/form-9'
      fullPath: '/form-9'
      preLoaderRoute: typeof Form9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-a': {
      id: '/form-a'
      path: '/form-a'
      fullPath: '/form-a'
      preLoaderRoute: typeof FormARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incorporation': {
      id: '/incorporation'
      path: '/incorporation'
      fullPath: '/incorporation'
      preLoaderRoute: typeof IncorporationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-assistant': {
      id: '/tax-assistant'
      path: '/tax-assistant'
      fullPath: '/tax-assistant'
      preLoaderRoute: typeof TaxAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve/$token': {
      id: '/approve/$token'
      path: '/approve/$token'
      fullPath: '/approve/$token'
      preLoaderRoute: typeof ApproveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/chat': {
      id: '/citizen/chat'
      path: '/citizen/chat'
      fullPath: '/citizen/chat'
      preLoaderRoute: typeof CitizenChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/documents': {
      id: '/citizen/documents'
      path: '/citizen/documents'
      fullPath: '/citizen/documents'
      preLoaderRoute: typeof CitizenDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/lawyers': {
      id: '/citizen/lawyers'
      path: '/citizen/lawyers'
      fullPath: '/citizen/lawyers'
      preLoaderRoute: typeof CitizenLawyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/companies/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/': {
      id: '/help-desk/'
      path: '/help-desk'
      fullPath: '/help-desk/'
      preLoaderRoute: typeof HelpDeskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/cyber-report': {
      id: '/help-desk/cyber-report'
      path: '/help-desk/cyber-report'
      fullPath: '/help-desk/cyber-report'
      preLoaderRoute: typeof HelpDeskCyberReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/police-encounter': {
      id: '/help-desk/police-encounter'
      path: '/help-desk/police-encounter'
      fullPath: '/help-desk/police-encounter'
      preLoaderRoute: typeof HelpDeskPoliceEncounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/succession': {
      id: '/help-desk/succession'
      path: '/help-desk/succession'
      fullPath: '/help-desk/succession'
      preLoaderRoute: typeof HelpDeskSuccessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/tenant-protection': {
      id: '/help-desk/tenant-protection'
      path: '/help-desk/tenant-protection'
      fullPath: '/help-desk/tenant-protection'
      preLoaderRoute: typeof HelpDeskTenantProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-desk/utility-dispute': {
      id: '/help-desk/utility-dispute'
      path: '/help-desk/utility-dispute'
      fullPath: '/help-desk/utility-dispute'
      preLoaderRoute: typeof HelpDeskUtilityDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$matterId': {
      id: '/matters/$matterId'
      path: '/matters/$matterId'
      fullPath: '/matters/$matterId'
      preLoaderRoute: typeof MattersMatterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/deadline-reminders': {
      id: '/api/cron/deadline-reminders'
      path: '/api/cron/deadline-reminders'
      fullPath: '/api/cron/deadline-reminders'
      preLoaderRoute: typeof ApiCronDeadlineRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId_/edit': {
      id: '/companies/$companyId_/edit'
      path: '/companies/$companyId/edit'
      fullPath: '/companies/$companyId/edit'
      preLoaderRoute: typeof CompaniesCompanyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ComplianceRoute: ComplianceRoute,
  ConsultRoute: ConsultRoute,
  ConsultationsRoute: ConsultationsRoute,
  ContractsRoute: ContractsRoute,
  CorporateFilingsRoute: CorporateFilingsRoute,
  DashboardRoute: DashboardRoute,
  Form9Route: Form9Route,
  FormARoute: FormARoute,
  GuideRoute: GuideRoute,
  IncorporationRoute: IncorporationRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TaxAssistantRoute: TaxAssistantRoute,
  TermsRoute: TermsRoute,
  ApproveTokenRoute: ApproveTokenRoute,
  CitizenChatRoute: CitizenChatRoute,
  CitizenDocumentsRoute: CitizenDocumentsRoute,
  CitizenLawyersRoute: CitizenLawyersRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesNewRoute: CompaniesNewRoute,
  HelpDeskCyberReportRoute: HelpDeskCyberReportRoute,
  HelpDeskPoliceEncounterRoute: HelpDeskPoliceEncounterRoute,
  HelpDeskSuccessionRoute: HelpDeskSuccessionRoute,
  HelpDeskTenantProtectionRoute: HelpDeskTenantProtectionRoute,
  HelpDeskUtilityDisputeRoute: HelpDeskUtilityDisputeRoute,
  MattersMatterIdRoute: MattersMatterIdRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  HelpDeskIndexRoute: HelpDeskIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDeadlineRemindersRoute: ApiCronDeadlineRemindersRoute,
  CompaniesCompanyIdEditRoute: CompaniesCompanyIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
