/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as Form9RouteImport } from './routes/form-9'
import { Route as FormARouteImport } from './routes/form-a'
import { Route as GuideRouteImport } from './routes/guide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const Form9Route = Form9RouteImport.update({
  id: '/form-9',
  path: '/form-9',
  getParentRoute: () => rootRouteImport,
} as any)
const FormARoute = FormARouteImport.update({
  id: '/form-a',
  path: '/form-a',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/checkout': typeof CheckoutRoute
  '/contracts': typeof ContractsRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/checkout': typeof CheckoutRoute
  '/contracts': typeof ContractsRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/checkout': typeof CheckoutRoute
  '/contracts': typeof ContractsRoute
  '/form-9': typeof Form9Route
  '/form-a': typeof FormARoute
  '/guide': typeof GuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/checkout'
    | '/contracts'
    | '/form-9'
    | '/form-a'
    | '/guide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/checkout'
    | '/contracts'
    | '/form-9'
    | '/form-a'
    | '/guide'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/checkout'
    | '/contracts'
    | '/form-9'
    | '/form-a'
    | '/guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContractsRoute: typeof ContractsRoute
  Form9Route: typeof Form9Route
  FormARoute: typeof FormARoute
  GuideRoute: typeof GuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-9': {
      id: '/form-9'
      path: '/form-9'
      fullPath: '/form-9'
      preLoaderRoute: typeof Form9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-a': {
      id: '/form-a'
      path: '/form-a'
      fullPath: '/form-a'
      preLoaderRoute: typeof FormARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  CheckoutRoute: CheckoutRoute,
  ContractsRoute: ContractsRoute,
  Form9Route: Form9Route,
  FormARoute: FormARoute,
  GuideRoute: GuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
